answers = [
  'It is certain',
  'Without a doubt',
  'Absolutely',
  'You may rely on it',
  'Indeed',
  'Most likely',
  'Outlook good',
  'I sure hope so',
  'Yes',
  'Signs point to yes',
  'Reply hazy try again',
  'Ask again later',
  'Better not tell you now',
  'Cannot predict now',
  'Concentrate and try again',
  'Dont count on it',
  'No way Jose',
  'Sources say no',
  'Nah brah',
  'No bro',
  'No',
  'Very doubtful',
  'Are you kidding mate']
